### ISSUE TITLE
copy does not overriting file if same file but different permissions

### ISSUE THREAD

**Issue by knutov** [umputun/spot#115]
```
      - name: copy pub key
        copy: {"src": "keys/id_ed25519.pub", "dst": "/tmp/spot.key"}
```

first run original file was 644 and was copied with 644 permissions.

Then permissions was set to 600, spot was run again and the file was still 644.

Also it could be very useful to have ability to copy file to remote file created by `mktemp` (to have random name and limited access) with exporting that filename to some variable

**Comment by umputun** [comment]
I think this is a deficiency in https://github.com/umputun/spot/issues/77 which does by default "quick check" what includes modification time and size only
