### ISSUE TITLE
Add support `ansible-vault` format for secrets

### ISSUE THREAD

**Issue by f100024** [umputun/spot#120]
Is it make sense for community add support `ansible-vault` format for secrets?
It could be useful in migration from `ansible` to spot, when you save your encrypted secrets in the repository, also this could be actual for small projects.

More information about [ansible-vault](https://docs.ansible.com/ansible/latest/vault_guide/vault.html)

**Comment by umputun** [comment]
Adding ansible-vault support would be useful. I don't see any popular libraries for go doing it, quick googling revealed just https://github.com/sosedoff/ansible-vault-go. I guess not many people have such a use case and maybe this library is fine 

If you want to add ansible-vault support to the Spot pls let me know
