### ISSUE TITLE
Indicating multiple task through the command-line options

### ISSUE THREAD

**Issue by ifraixedes** [umputun/spot#131]
According to the docs `spot` executes all the tasks in the playbook if the `--task` option is passed to the command.

Is there any reason why this option cannot be specified multiple times as `--target, -t` for indicating to execute more than one task?

**Comment by umputun** [comment]
Good point. Technically it is already possible to run multiple tasks (if no `--task` is set); however, it is running all the tasks and not allowing to set the list of tasks.

I don't recall the reason for this; probably, I have not considered this use case as something valid. Either way I think this is a nice thing to have and should be relatively easy to implement.

**Comment by ifraixedes** [comment]
Ok, good.
I may try to take a look at it this week, but I don't promise.

**Comment by ifraixedes** [comment]
Fine to me, I didn't find the time last week, and I doubt that I was going to find it this week.
Anyway, the improvement was nice to have for me because calling `spot` more than one passing the task isn't a problem for me because I need to perform more operations before calling it and I have all of them under a Makefile target.
