### ISSUE TITLE
Windows binary works incorrect

### ISSUE THREAD

**Issue by shikhov** [umputun/spot#138]
It creates files on remote side with wrong slashes:
![image](https://github.com/umputun/spot/assets/9966764/ca004687-6177-4b46-9edc-e1a94d6db880)

**Comment by umputun** [comment]
What exactly is wrong with this? Isn't windows using `\` instead of the usual `/`

**Comment by shikhov** [comment]
It is Linux on screenshot, so Spot cannot run script on remote side due to wrong filename.
Windows, btw, support both of slashes.

**Comment by umputun** [comment]
So, this is the case with the host running spot is windows but the destination nodes are linux. In this case, I do understand what's going on - the host doesn't have a clue what the destination machine is and making tmp path with `filepath.Join` which leads to this.

I think the simplest solution is to enforce linux `/` regardless of what host OS is

**Comment by umputun** [comment]
pls check if the latest 1.10.0 solved the issue
