### ISSUE TITLE
Add support of env and secrets to onerror action

### ISSUE THREAD

**Issue by umputun** [umputun/spot#178]
### Discussed in https://github.com/umputun/spot/discussions/177

<div type='discussions-op-text'>

<sup>Originally posted by **rahfar** March 21, 2024</sup>
Hi, I want to add notification to telegram on error. Do not want to hardcode bot token in playbook, is it possible to use env vars or secrets in on_error field?</div>

**Comment by rahfar** [comment]
I assume it could be closed - at least, I am fully satisfied with the new availability of setting secrets, and environment variables at the task level. thanks
