### ISSUE TITLE
ssh_key in inventory

### ISSUE THREAD

**Issue by polderudo** [umputun/spot#224]
Would it be possible to add the ssh_key also to the inventory file?
Right how we use a `ssh_key: ~/.ssh/deploy_rsa.private` and every user copies his private file to this location. Works ok, but would be nicer if we can define the file on the invertory yml.
I mean we can define the user there, why not the ssh_key?

Nice lib btw. Replacing ansible for us and works also on Windows!

**Comment by umputun** [comment]
This is an interesting idea, and should be straightforward to implement it.

**Comment by polderudo** [comment]
We currently moved to have all config in the spot file directly. We run ok with this and do not need to take care on every users envirement, this way.
