### ISSUE TITLE
Freezing features set in preparation for v1.0.0 

### ISSUE THREAD

**Issue by umputun** [umputun/spot#63]
All the functionality I have planned for v1.0.0 is in place. From now on, I'd like to observe how it works in real life and collect (and eventually fix) all the possible issues for both the technical and UX sides.

Please feel free to report your experience and suggest minor changes to the existing functionality to make it convenient.

**Comment by bessarabov** [comment]
How long are you planning to collect issues before going live with 1.0.0?

**Comment by umputun** [comment]
nobody knows - as long as it takes to be certain that the latest version doesn't have any issues we know about

**Comment by umputun** [comment]
The current master is stable enough to become v1. It may have some minor bugs we have yet to discover, but generally, it is solid. 

The api is stabilized, and no breaking change for either command line of the playbook/inventory format is planned. The code was cleaned and refactored to be easy to read and contribute to. The set of tests is comprehensive and the docs seem to be sufficient.
