### ISSUE TITLE
Make it installable by brew

### ISSUE THREAD

**Issue by umputun** [umputun/spot#7]
Not sure, what is involved, never did it, but probably goreleaser we are using could do it

**Comment by olegmlsn** [comment]
GoReleaser cannot generate valid formulas for Homebrew-core, only for Taps (Third-Party Repositories) https://docs.brew.sh/Taps.html. Taps involves using a Github repository to store and access formulas.

It may be convenient to use a separate repository for Homebrew formulas, for example umputun/homebrew-apps. Formulas for other utilities could also be added there. In this case, the installation would look like this:

```
brew tap umputun/apps
brew install umputun/apps/spot
```

Unfortunately, there is already a package called "spot" in Homebrew-core, so when using the unique name, you have to pass the formula name along with the path to brew install. If a unique name is used, only the name can be passed in the "install" command.

As a test, I added a "brews" section to goreleaser.yml and added a copy of the formula to Dockerfile.release. I ran "make release" locally and got a valid formula for Homebrew.

GoReleaser can push the formula directly to the formula repository, but in the Dockerfile.release of spot, it is run with the `--skip-publish` option. Unfortunately, I have not fully understood the release mechanism in spot yet. Therefore, I manually moved the obtained file to a separate repository https://github.com/olegmlsn/homebrew-apps.

You can try it like this:

```
brew tap olegmlsn/apps
brew install olegmlsn/apps/spot
```

The PR #81  is only for ease of viewing.

Is installation using homebrew taps suitable for you? 
Are there any considerations to keep in mind?

Sorry for my English

**Comment by umputun** [comment]
thx. The release is not that complicated. All it does is build artifacts with gorleleaser inside the container and put it to .bin/artifacts of the host. As I release binary, I'm uploading them all manually to gihub. I don't recall what was the initial reason why this goreleaser thing runs in a container, maybe it is not even needed anymore. My goreleaser experience is very limited, so feel free to improve the flow.

Regarding your PR - I have tried it, and it produced `spot.rb`. Can you advise how I publish this tap? Quick googling mentions a separate git repo for this, but I don't care enough to make a separate repo and would like to keep it as simple as possible. If this is doable can you pls add a Makefile target "brew" publishing this tap?

**Comment by umputun** [comment]
I have added half-backed automation running release.yml pipeline and publishing things, including brew. Pls take a look and make it right if you like ;)

**Comment by olegmlsn** [comment]
Unfortunately, `brew tap repo` clones the entire repository to the user's device. I think using a separate repository is not the worst solution. With GoReleaser and its commits during release, this looks like keeping it simple.

If you create a repository, I could make the remaining changes.

Is adding tap publication to the makefile still necessary?

In my opinion, everything looks fine in release.yml.

**Comment by umputun** [comment]
ok, I made the repo and restored the `name` to the original `homebrew-apps` as you suggested. 

> Is adding tap publication to the makefile still necessary?

nah, not needed to publish to brew, as the Makefie just build binaries, not publishes them. I think the current `release` target does it as is

**Comment by olegmlsn** [comment]
It works great. Thank you!

<img width="568" alt="spot_brew" src="https://github.com/umputun/spot/assets/35684941/9a3c7173-d04b-42d2-9bcf-450482d97e7f">

**Comment by umputun** [comment]
@olegmlsn any idea why the `release` thing is so slow on GitHub actions? Locally it runs very fast, like a few seconds, but on github it takes 3+ minutes. This is not something that critical, but rather surprising

**Comment by olegmlsn** [comment]
The reason may be in actions/setup-go@v4. It's just a guess. Changes in v4 are related only to caching, but it's worth checking. If possible, change it to v3 and check.
