### ISSUE TITLE
[proposal] Checking state before running

### ISSUE THREAD

**Issue by korney4eg** [umputun/spot#77]
My idea come from ansible, where before copying file it checks hashsum on remote and locally.

I understand that it will increase complexity, but probably it will help in some ways.

**Comment by korney4eg** [comment]
Seems like it was implemented. Should I close this issue?

**Comment by umputun** [comment]
The implementation is similar to rsync's quick matching method, i.e. it doesn't do hashsum/checksum but just checks the file sizes and modification times. I'm planning to add checksum method as an option, but I think for the majority of use cases, this quick method will do

Feel free to close if this is sufficient for you.

**Comment by korney4eg** [comment]
closing. Thank you for implementing
