### ISSUE TITLE
Add exclude support to other commands

### ISSUE THREAD

**Issue by umputun** [umputun/spot#98]
I have added `exclude` support for `sync` command; see https://github.com/umputun/spot/pull/97. This is the most obvious use case for exclusion; however, all other commands that support glob can be extended like this. I.e. copy, delete, mcopy

**Comment by Gauravvpnd** [comment]
I would love to work on this issue can you assign me this?

**Comment by umputun** [comment]
sure, all yours

**Comment by Gauravvpnd** [comment]
> sure, all yours

Thank you i will fix this asap.

**Comment by umputun** [comment]
thx; feel free to reach out if any questions. hopefully, you will find the code easy to read; at least this was one of my goals ;)

**Comment by umputun** [comment]
@Gauravvpnd what's up with this one? Still planning to do it or gave up?

**Comment by bakurin** [comment]
I'm taking over if there is no objection.
